import { useState } from 'react'
import { Activity, Building2, CheckCircle2, Clock3, Database, GitBranch, MessageSquareText, RefreshCw, Search, SlidersHorizontal, UserRound, Zap } from 'lucide-react'
import { contextSignals } from '../data/recommendationData'
import JourneyFooter from '../components/JourneyFooter'

const sources = [
  { name: 'Salesforce', type: 'CRM', status: 'Healthy', records: '14.2K', freshness: '8 min', icon: Database, color: 'bg-blue-100 text-blue-700' },
  { name: 'Mindtickle Call AI', type: 'Call intelligence', status: 'Healthy', records: '3.8K', freshness: '18 min', icon: MessageSquareText, color: 'bg-violet-100 text-violet-700' },
  { name: 'Activity stream', type: 'Email & meetings', status: 'Healthy', records: '86.4K', freshness: '3 min', icon: Activity, color: 'bg-emerald-100 text-emerald-700' },
  { name: 'Custom objects', type: 'Tenant schema', status: 'Mapping review', records: '1.1K', freshness: '2 hr', icon: GitBranch, color: 'bg-amber-100 text-amber-700' },
]

export default function ContextExplorer() {
  const [selected, setSelected] = useState(1)
  const [refreshing, setRefreshing] = useState(false)
  return <div className="max-w-[1400px] mx-auto p-6 lg:p-8">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-7"><div><div className="text-xs font-semibold text-violet-700 mb-2">CONTEXT INTELLIGENCE</div><h1 className="text-[28px] font-semibold tracking-tight text-slate-900">Context Explorer</h1><p className="text-sm text-slate-500 mt-1.5">Inspect the authorized signals shaping recommendations and diagnose source quality.</p></div><button onClick={() => {setRefreshing(true); setTimeout(() => setRefreshing(false), 1000)}} className="px-4 py-2.5 bg-white border border-slate-200 rounded-lg text-sm font-medium text-slate-700 flex items-center gap-2 panel-shadow"><RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} /> Refresh sources</button></div>

    <div className="grid grid-cols-1 lg:grid-cols-[360px_1fr] gap-5">
      <div className="space-y-5">
        <div className="bg-white border border-slate-200 rounded-2xl panel-shadow p-4"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input className="w-full pl-9 pr-3 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm outline-none" value="Acme Corp" readOnly /></div><div className="flex items-center gap-2 mt-3"><button className="px-3 py-1.5 text-xs rounded-lg bg-slate-900 text-white">Opportunity</button><button className="px-3 py-1.5 text-xs rounded-lg border border-slate-200 text-slate-500">Account</button><button className="ml-auto p-1.5 text-slate-400"><SlidersHorizontal size={14} /></button></div></div>
        <div className="bg-white border border-slate-200 rounded-2xl panel-shadow overflow-hidden"><div className="px-4 py-3.5 border-b border-slate-100"><div className="text-sm font-semibold text-slate-900">Connected sources</div><div className="text-xs text-slate-500 mt-0.5">4 sources · 105.5K records</div></div><div className="p-2">{sources.map((source, i) => {const Icon=source.icon; return <button key={source.name} onClick={() => setSelected(i)} className={`w-full p-3 rounded-xl text-left flex items-center gap-3 ${selected === i ? 'bg-violet-50 ring-1 ring-violet-100' : 'hover:bg-slate-50'}`}><div className={`w-9 h-9 rounded-lg flex items-center justify-center ${source.color}`}><Icon size={16} /></div><div className="flex-1"><div className="text-xs font-semibold text-slate-800">{source.name}</div><div className="text-[11px] text-slate-400 mt-0.5">{source.type} · {source.records}</div></div><span className={`w-2 h-2 rounded-full ${source.status === 'Healthy' ? 'bg-emerald-500' : 'bg-amber-500'}`} /></button>})}</div></div>
      </div>

      <div className="space-y-5">
        <div className="bg-white border border-slate-200 rounded-2xl panel-shadow p-5"><div className="flex items-start justify-between"><div><div className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Resolved revenue context</div><h2 className="text-lg font-semibold text-slate-900 mt-1.5">Acme Corp · Expansion opportunity</h2><div className="flex flex-wrap gap-2 mt-2"><span className="text-xs text-slate-500">Opportunity <b className="text-slate-700">OPP-1842</b></span><span className="text-slate-300">•</span><span className="text-xs text-slate-500">Snapshot <b className="text-slate-700">CTX-456</b></span><span className="text-slate-300">•</span><span className="text-xs text-emerald-600 font-medium">92% complete</span></div></div><span className="px-2.5 py-1.5 rounded-full bg-emerald-50 text-emerald-700 text-xs font-medium flex items-center gap-1.5"><CheckCircle2 size={13} /> Permission safe</span></div>
          <div className="mt-6 soft-grid rounded-xl border border-slate-200 p-6 overflow-hidden"><div className="relative min-h-[280px] flex items-center justify-center"><div className="absolute left-1/2 top-1/2 w-[420px] h-px bg-slate-200 -translate-x-1/2" /><div className="absolute left-1/2 top-1/2 w-px h-[210px] bg-slate-200 -translate-y-1/2" /><div className="relative z-10 w-32 h-32 rounded-full bg-slate-900 text-white flex flex-col items-center justify-center shadow-xl"><Building2 size={22} /><div className="text-sm font-semibold mt-2">Acme Corp</div><div className="text-[10px] text-slate-400">Account</div></div><div className="absolute left-[8%] top-[16%] z-10 bg-white rounded-xl border border-blue-200 p-3 w-36 panel-shadow"><Database size={14} className="text-blue-600" /><div className="text-xs font-semibold mt-2">Opportunity</div><div className="text-[10px] text-slate-400 mt-1">$420K · Proposal</div></div><div className="absolute right-[8%] top-[16%] z-10 bg-white rounded-xl border border-violet-200 p-3 w-36 panel-shadow"><MessageSquareText size={14} className="text-violet-600" /><div className="text-xs font-semibold mt-2">Latest call</div><div className="text-[10px] text-slate-400 mt-1">ROI concern</div></div><div className="absolute left-[8%] bottom-[12%] z-10 bg-white rounded-xl border border-rose-200 p-3 w-36 panel-shadow"><UserRound size={14} className="text-rose-600" /><div className="text-xs font-semibold mt-2">3 contacts</div><div className="text-[10px] text-slate-400 mt-1">1 economic buyer</div></div><div className="absolute right-[8%] bottom-[12%] z-10 bg-white rounded-xl border border-emerald-200 p-3 w-36 panel-shadow"><Activity size={14} className="text-emerald-600" /><div className="text-xs font-semibold mt-2">Activity</div><div className="text-[10px] text-slate-400 mt-1">Engagement +34%</div></div></div></div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div className="bg-white border border-slate-200 rounded-2xl panel-shadow p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-slate-900">Signals used in ranking</h3><Zap size={15} className="text-amber-500" /></div><div className="mt-4 space-y-3">{contextSignals.slice(0,4).map(signal => <div key={signal.type}><div className="flex justify-between text-xs"><span className="text-slate-600">{signal.type}</span><span className="font-medium text-slate-800">{signal.strength}%</span></div><div className="h-1.5 bg-slate-100 rounded-full mt-1.5"><div className="h-full bg-violet-500 rounded-full" style={{width:`${signal.strength}%`}} /></div></div>)}</div></div><div className="bg-white border border-slate-200 rounded-2xl panel-shadow p-5"><h3 className="text-sm font-semibold text-slate-900">Source diagnostics</h3><div className="mt-4 space-y-3"><div className="flex items-center justify-between p-3 bg-emerald-50 rounded-xl"><span className="text-xs text-emerald-800">Entity resolution</span><span className="text-xs font-semibold text-emerald-700">98.6%</span></div><div className="flex items-center justify-between p-3 bg-slate-50 rounded-xl"><span className="text-xs text-slate-600">Oldest active signal</span><span className="text-xs font-semibold text-slate-800 flex items-center gap-1"><Clock3 size={11}/> 4 days</span></div><div className="flex items-center justify-between p-3 bg-slate-50 rounded-xl"><span className="text-xs text-slate-600">Excluded sensitive fields</span><span className="text-xs font-semibold text-slate-800">7</span></div></div></div></div>
      </div>
    </div>
    <JourneyFooter completed="Context intelligence made inspectable" insight="The platform resolves heterogeneous revenue signals into a permission-safe, freshness-aware snapshot that every recommendation surface can reuse." previous={{label:'Seller experience',to:'/recommendations'}} next={{label:'Apply enterprise control',to:'/governance',description:'Inspect policy, eligibility, and audit decisions'}} />
  </div>
}
