import { useState } from 'react'
import { AlertTriangle, CheckCircle2, ChevronRight, PlusCircle, FileLock2, Filter, History, KeyRound, Search, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import { policies } from '../data/recommendationData'

export default function GovernanceConsole() {
  const [policyState, setPolicyState] = useState(policies)
  const toggle = (id:string) => setPolicyState(policyState.map(p => p.id === id ? {...p, status: !p.status} : p))
  return <div className="max-w-[1400px] mx-auto p-6 lg:p-8">
    <div className="flex items-end justify-between mb-7"><div><div className="text-xs font-semibold text-violet-700 mb-2">ENTERPRISE CONTROL PLANE</div><h1 className="text-[28px] font-semibold tracking-tight text-slate-900">Governance & policy</h1><p className="text-sm text-slate-500 mt-1.5">Define what the recommendation service may use, return, and expose on each surface.</p></div><button className="px-4 py-2.5 bg-slate-900 text-white rounded-lg text-sm font-medium flex items-center gap-2"><PlusCircle size={15}/> New policy</button></div>
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-5">{[{label:'Active policies',value:'12',icon:ShieldCheck,color:'text-emerald-600 bg-emerald-50'},{label:'Policy checks · 24h',value:'18.4K',icon:Filter,color:'text-violet-600 bg-violet-50'},{label:'Blocked candidates',value:'1,248',icon:FileLock2,color:'text-amber-600 bg-amber-50'},{label:'Critical violations',value:'0',icon:CheckCircle2,color:'text-emerald-600 bg-emerald-50'}].map(item => {const Icon=item.icon; return <div key={item.label} className="bg-white rounded-2xl border border-slate-200 panel-shadow p-4 flex items-center gap-3"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${item.color}`}><Icon size={18}/></div><div><div className="text-xl font-semibold text-slate-900">{item.value}</div><div className="text-[11px] text-slate-500 mt-0.5">{item.label}</div></div></div>})}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[1fr_350px] gap-5"><div className="bg-white rounded-2xl border border-slate-200 panel-shadow overflow-hidden"><div className="p-4 border-b border-slate-100 flex items-center justify-between"><div className="relative w-72"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input placeholder="Search policies" className="w-full pl-9 pr-3 py-2 rounded-lg bg-slate-50 border border-slate-200 text-sm"/></div><button className="p-2 border border-slate-200 rounded-lg text-slate-500"><SlidersHorizontal size={15}/></button></div><div className="divide-y divide-slate-100">{policyState.map(policy => <div key={policy.id} className="p-5 flex items-start gap-4 hover:bg-slate-50/50"><div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${policy.status ? 'bg-violet-50 text-violet-600' : 'bg-slate-100 text-slate-400'}`}><ShieldCheck size={17}/></div><div className="flex-1"><div className="flex items-center gap-2"><h3 className="text-sm font-semibold text-slate-900">{policy.name}</h3><span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-500">{policy.type}</span></div><p className="text-xs text-slate-500 mt-1.5">{policy.description}</p><div className="text-[11px] text-slate-400 mt-2">Scope: {policy.scope} · Last changed by Priya N.</div></div><button onClick={() => toggle(policy.id)} className={`w-10 h-6 rounded-full p-1 transition-colors ${policy.status ? 'bg-violet-600' : 'bg-slate-300'}`}><span className={`block w-4 h-4 rounded-full bg-white transition-transform ${policy.status ? 'translate-x-4' : ''}`}/></button><ChevronRight size={16} className="text-slate-300 mt-1"/></div>)}</div></div>
      <div className="space-y-5"><div className="bg-slate-900 rounded-2xl text-white panel-shadow p-5"><div className="flex items-center gap-2 text-sm font-semibold"><KeyRound size={16} className="text-violet-300"/> Decision trace</div><p className="text-xs text-slate-400 leading-relaxed mt-2">Inspect why a candidate was allowed, boosted, or suppressed without exposing restricted context.</p><div className="mt-4 bg-white/5 border border-white/10 rounded-xl p-3"><div className="text-[10px] text-slate-400">Recommendation ID</div><div className="font-mono text-xs mt-1">rec_789_acme_roi</div></div><button className="w-full mt-3 py-2.5 rounded-lg bg-violet-600 text-xs font-medium">Inspect trace</button></div><div className="bg-white rounded-2xl border border-slate-200 panel-shadow p-5"><div className="flex items-center gap-2"><History size={15} className="text-slate-500"/><h3 className="text-sm font-semibold text-slate-900">Recent changes</h3></div><div className="mt-4 space-y-4">{['Required security brief enabled','Healthcare field allowlist updated','Outcome-aware ranking paused'].map((x,i)=><div key={x} className="flex gap-3"><span className={`mt-1.5 w-2 h-2 rounded-full shrink-0 ${i===2?'bg-amber-500':'bg-emerald-500'}`}/><div><div className="text-xs text-slate-700">{x}</div><div className="text-[10px] text-slate-400 mt-1">{i+1} day{i?'s':''} ago · Admin</div></div></div>)}</div></div><div className="bg-amber-50 rounded-2xl border border-amber-200 p-4"><div className="flex gap-2"><AlertTriangle size={15} className="text-amber-600 shrink-0"/><div><div className="text-xs font-semibold text-amber-900">1 mapping needs review</div><p className="text-[11px] text-amber-700 mt-1 leading-relaxed">Partner Deal custom object has 3 unmapped fields. Existing recommendations are unaffected.</p></div></div></div></div>
    </div>
  </div>
}
