import { ArrowRight, Braces, Check, ChevronRight, CircleDot, Database, FileText, Layers3, LockKeyhole, MousePointer2, Orbit, ShieldCheck, Sparkles, Target, Wand2, Zap } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

const journey = [
  { number: '01', title: 'Seller experience', text: 'A seller gets three approved assets for a live opportunity—ranked and explained.', to: '/recommendations', icon: Wand2, color: 'violet' },
  { number: '02', title: 'Context intelligence', text: 'See how opportunity, account, contact, call, and activity signals resolve into context.', to: '/context', icon: Orbit, color: 'blue' },
  { number: '03', title: 'Trust & control', text: 'Inspect eligibility, permissions, suppression, policy trace, and audit controls.', to: '/governance', icon: ShieldCheck, color: 'emerald' },
  { number: '04', title: 'Open delivery', text: 'Use one governed contract across CRM, REST, events, embedded apps, and MCP.', to: '/developer', icon: Braces, color: 'cyan' },
]

const colorMap: Record<string, string> = { violet: 'bg-violet-100 text-violet-700', blue: 'bg-blue-100 text-blue-700', emerald: 'bg-emerald-100 text-emerald-700', cyan: 'bg-cyan-100 text-cyan-700' }

export default function PlatformOverview() {
  const navigate = useNavigate()
  return <div className="min-h-full">
    <section className="relative overflow-hidden bg-[#0d1529] text-white">
      <div className="absolute inset-0 opacity-30" style={{backgroundImage:'radial-gradient(circle at 70% 20%, #7c3aed 0, transparent 30%), radial-gradient(circle at 85% 80%, #2563eb 0, transparent 26%)'}} />
      <div className="absolute inset-0 soft-grid opacity-[0.08]" />
      <div className="relative max-w-[1400px] mx-auto px-6 lg:px-8 py-14 lg:py-20 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-violet-300/20 bg-violet-300/10 text-xs text-violet-200"><Sparkles size={13} /> Rebuilding content recommendations as a platform</div>
          <h1 className="text-4xl lg:text-[54px] leading-[1.06] tracking-[-0.035em] font-semibold mt-6">The right content for this buyer, at this moment, on any surface.</h1>
          <p className="text-base lg:text-lg text-slate-300 leading-relaxed mt-5 max-w-2xl">Move from opportunity-field rules inside one CRM to a governed intelligence service that understands revenue context, explains every result, and serves customers, partners, and agents.</p>
          <div className="flex flex-wrap gap-3 mt-8"><button onClick={() => navigate('/recommendations')} className="px-5 py-3 rounded-xl bg-violet-600 hover:bg-violet-500 text-sm font-semibold flex items-center gap-2 shadow-lg shadow-violet-950/40"><MousePointer2 size={16} /> Start guided walkthrough <ArrowRight size={15} /></button><button onClick={() => document.getElementById('strategy')?.scrollIntoView({behavior:'smooth'})} className="px-5 py-3 rounded-xl border border-white/15 bg-white/[0.04] hover:bg-white/[0.08] text-sm font-medium">See the strategy</button></div>
          <div className="flex flex-wrap gap-x-6 gap-y-2 mt-8 text-xs text-slate-400">{['Content-first scope','Hybrid AI + rules','Enterprise controls by design'].map(x => <span key={x} className="flex items-center gap-1.5"><Check size={13} className="text-emerald-400" /> {x}</span>)}</div>
        </div>

        <div className="relative">
          <div className="rounded-3xl border border-white/10 bg-white/[0.06] backdrop-blur p-4 lg:p-5 shadow-2xl shadow-black/30">
            <div className="flex items-center justify-between pb-4 border-b border-white/10"><div><div className="text-[10px] uppercase tracking-[0.15em] text-slate-400">Flagship use case</div><div className="text-sm font-semibold mt-1">Opportunity preparation · Acme Corp</div></div><span className="text-[10px] px-2 py-1 rounded-full bg-emerald-400/10 text-emerald-300">18 signals live</span></div>
            <div className="grid grid-cols-[1fr_auto_1fr] gap-3 items-center py-5"><div className="space-y-2">{['Latest call: ROI concern','Account: Manufacturing','Activity: Security interest'].map((x,i)=><div key={x} className="rounded-lg bg-white/[0.06] border border-white/[0.08] p-2.5 text-[11px] text-slate-300 flex items-center gap-2"><span className={`w-1.5 h-1.5 rounded-full ${i===0?'bg-violet-400':i===1?'bg-blue-400':'bg-emerald-400'}`} />{x}</div>)}</div><ChevronRight className="text-violet-300" size={18}/><div className="rounded-2xl bg-white text-slate-900 p-4"><div className="flex items-center gap-2 text-[10px] uppercase tracking-wide font-semibold text-violet-600"><FileText size={13}/> #1 recommendation</div><div className="text-sm font-semibold mt-2">Enterprise ROI Guide</div><div className="text-[11px] text-slate-500 mt-1.5">94% confidence · Approved</div><div className="mt-3 h-1.5 bg-slate-100 rounded-full"><div className="h-full w-[94%] bg-violet-500 rounded-full"/></div></div></div>
            <div className="grid grid-cols-3 gap-2">{[{label:'Context',value:'5 sources',icon:Database},{label:'Control',value:'3 policies',icon:LockKeyhole},{label:'Delivery',value:'Any surface',icon:Zap}].map(item=>{const Icon=item.icon;return <div key={item.label} className="rounded-xl bg-white/[0.05] border border-white/[0.08] p-3"><Icon size={14} className="text-violet-300"/><div className="text-[10px] text-slate-500 mt-2">{item.label}</div><div className="text-xs font-medium mt-0.5">{item.value}</div></div>})}</div>
          </div>
        </div>
      </div>
    </section>

    <div className="max-w-[1400px] mx-auto px-6 lg:px-8 py-10 lg:py-14">
      <section id="strategy">
        <div className="max-w-3xl"><div className="text-xs uppercase tracking-[0.16em] font-semibold text-violet-600">Strategic shift</div><h2 className="text-2xl lg:text-3xl font-semibold tracking-tight text-slate-900 mt-2">Preserve customer control. Remove the structural ceilings.</h2><p className="text-sm text-slate-500 leading-relaxed mt-3">The strategy is not “replace rules with an LLM.” Rules continue to govern eligibility and policy; context-aware retrieval and ranking handle relevance.</p></div>
        <div className="grid lg:grid-cols-[1fr_auto_1fr] gap-4 items-stretch mt-7">
          <div className="rounded-2xl bg-white border border-slate-200 p-6 panel-shadow"><div className="text-[11px] uppercase tracking-wider font-semibold text-slate-400">Current engine</div><h3 className="text-lg font-semibold text-slate-900 mt-2">One context. One surface. Static rules.</h3><div className="mt-5 space-y-3">{['Opportunity attributes only','Hand-maintained if/then matching','Content inside the CRM','Limited feedback and learning'].map(x=><div key={x} className="flex items-center gap-2.5 text-sm text-slate-600"><CircleDot size={14} className="text-slate-300" />{x}</div>)}</div></div>
          <div className="hidden lg:flex items-center justify-center"><div className="w-11 h-11 rounded-full bg-violet-600 text-white flex items-center justify-center shadow-lg"><ArrowRight size={18}/></div></div>
          <div className="rounded-2xl bg-gradient-to-br from-violet-50 to-blue-50 border border-violet-200 p-6 panel-shadow"><div className="text-[11px] uppercase tracking-wider font-semibold text-violet-600">Target platform</div><h3 className="text-lg font-semibold text-slate-900 mt-2">Any context. Governed intelligence. Any surface.</h3><div className="mt-5 space-y-3">{['Revenue objects + interaction signals','Hybrid retrieval, ranking, and policy','CRM, API, embedded, MCP, partners','Grounded explanations and feedback loop'].map(x=><div key={x} className="flex items-center gap-2.5 text-sm text-slate-700"><Check size={14} className="text-emerald-600" />{x}</div>)}</div></div>
        </div>
      </section>

      <section className="mt-14"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.16em] font-semibold text-violet-600">Guided prototype</div><h2 className="text-2xl font-semibold tracking-tight text-slate-900 mt-2">Follow value from signal to surface</h2></div><p className="text-sm text-slate-500 max-w-xl">Each screen answers a different panel question and hands off to the next capability in the platform story.</p></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mt-6">{journey.map(item=>{const Icon=item.icon;return <button key={item.number} onClick={()=>navigate(item.to)} className="text-left bg-white rounded-2xl border border-slate-200 p-5 panel-shadow hover:-translate-y-1 hover:border-violet-300 transition-all group"><div className="flex items-center justify-between"><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${colorMap[item.color]}`}><Icon size={18}/></div><span className="text-xs font-mono text-slate-300 group-hover:text-violet-500">{item.number}</span></div><h3 className="text-sm font-semibold text-slate-900 mt-5">{item.title}</h3><p className="text-xs text-slate-500 leading-relaxed mt-2 min-h-[48px]">{item.text}</p><div className="flex items-center gap-1.5 text-xs font-medium text-violet-700 mt-4">Explore <ArrowRight size={13}/></div></button>})}</div></section>

      <section className="mt-14 grid lg:grid-cols-[1fr_1fr] gap-5">
        <div className="rounded-2xl bg-white border border-slate-200 p-6 panel-shadow"><div className="flex items-center gap-2 text-sm font-semibold text-slate-900"><Target size={17} className="text-violet-600"/> Initial initiative</div><h3 className="text-xl font-semibold tracking-tight text-slate-900 mt-4">Multi-context content recommendations for opportunity preparation</h3><p className="text-sm text-slate-500 leading-relaxed mt-3">A bounded wedge that tests whether added account, contact, call, and activity context materially improves approved-content usefulness before investing in broad platform expansion.</p><div className="grid grid-cols-3 gap-3 mt-5">{[{v:'≤3',l:'results by default'},{v:'100%',l:'explained outputs'},{v:'0',l:'permission leaks'}].map(x=><div key={x.l} className="rounded-xl bg-slate-50 p-3"><div className="text-lg font-semibold text-slate-900">{x.v}</div><div className="text-[10px] text-slate-500 mt-1">{x.l}</div></div>)}</div></div>
        <div className="rounded-2xl bg-slate-900 text-white p-6 panel-shadow"><div className="flex items-center gap-2 text-sm font-semibold"><Layers3 size={17} className="text-violet-300"/> Evidence-gated roadmap</div><div className="mt-5 space-y-4">{[{n:'1',t:'Foundation & parity',d:'Shadow legacy behavior; prove trust and rollback.'},{n:'2',t:'Multi-context value',d:'Demonstrate lift over opportunity-only control.'},{n:'3',t:'Open delivery',d:'Stabilize contract, then expose API and MCP.'}].map((x,i)=><div key={x.n} className="flex gap-3"><div className={`w-7 h-7 rounded-full shrink-0 flex items-center justify-center text-xs font-semibold ${i===0?'bg-violet-600':'bg-white/10 text-slate-300'}`}>{x.n}</div><div><div className="text-xs font-semibold">{x.t}</div><div className="text-[11px] text-slate-400 mt-1">{x.d}</div></div></div>)}</div><button onClick={()=>navigate('/recommendations')} className="w-full mt-6 py-3 rounded-xl bg-violet-600 hover:bg-violet-500 text-xs font-semibold flex items-center justify-center gap-2">Experience the flagship workflow <ArrowRight size={14}/></button></div>
      </section>
    </div>
  </div>
}
